### ISSUE TITLE
Connection Closed

### ISSUE THREAD

**Issue by Raphitech** [debrosseda/DiscordSignal#1]
i uploaded your the modifyed sketch but i always see this message in my Serial Monitor :

Connected to Wifi, Connecting to WebSockets Server @wss://gateway.discord.gg/
Connnection Opened
Connected!
Got Message: {"t":null,"s":null,"op":10,"d":{"heartbeat_interval":41250,"_trace":["[\"gateway-prd-us-east1-d-hwjf\",{\"micros\":0.0}]"]}}
Recieved Heartbeat:41250
Send:: {"op":2,"d":{"token":"#########","intents":3714,"properties":{"$os":"linux","$browser":"ESP32","$device":"ESP32"},"compress":false,"large_threshold":250}}
Connnection Closed

**Comment by debrosseda** [comment]
That sounds like the discord server is unhappy with your "op":2 message. Did you set up all the permissions with the discord bot account to match your intents?

Also, don't post the clear text of your token anywhere. I edited your message to obscure it.

Here's a guide to bot account setup:
https://discordpy.readthedocs.io/en/stable/discord.html

Read Message/View Channels should be the key permissions for the sketch as posted. For scopes, you need bot, messages.read, guild.members.read (for voice status on login) and possibly rpc.notifications.read.

**Comment by Raphitech** [comment]
Thx for obscuring it
I tried to activate the said permissions but when activating the messages.read it wants me to insert a Redirect URL but i can't select or input anything and without it i can't generate the Bot URL

**Comment by debrosseda** [comment]
Looking again, I think you should be fine with just the bot scope under Setting>OAuth2 and the members and presences on the Settings>Bot page. 

https://discord.com/developers/docs/quick-start/getting-started

I'd try starting a new bot account from scratch and see if you can get it added to a personal discord test server (guild). Otherwise, your op:2 message looks just like mine (except the token). You should receive a "Ready event" in response if the bot account is set up right.
